### ISSUE TITLE
Move make_me to its own org

### ISSUE THREAD

**Issue by skalnik** [make-me/make-me#20]

**Comment by skalnik** [comment]
Anyone have an issue with me pulling the trigger to moving it over to `make-me/make-me`? /cc @ymendel @sshirokov @thedaniel

**Comment by ymendel** [comment]
Keeping it private for now?

**Comment by skalnik** [comment]
Yeah private for now, and then open source it when we can.

**Comment by ymendel** [comment]
Do it.

**Comment by thedaniel** [comment]
+1  

## 

Daniel Hengeveld
about.me/thedaniel

**Comment by sshirokov** [comment]
![engage.jpg](https://f.cloud.github.com/assets/40149/4283/7ac9c06c-4303-11e2-807c-e3fc3531516f.jpg)

**Comment by skalnik** [comment]
I actually realized that there's 1 big disadvantage to this. By moving it to an org outside of GitHub, new folks won't be directly exposed to this as easily. I think I'll hold off until we're actually make it open source.

**Comment by sshirokov** [comment]
We moved, closing
