### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by skalnik** [make-me/make-me#5]
There's no reason to keep this locked up, is there? Lets figure out how to open source this and share it with the world :sparkles:

**Comment by sshirokov** [comment]
No good reason. 

We just need to bump the hubot auth to the env

**Comment by skalnik** [comment]
A few things I want to see before unveiling this (for the awesomeness factor):
1. Lock file to take in any JSON hash and return it when checking for a lock. This will let people store whatever data they want in there :+1:
2. Our own print script, with the ability to ping campfire when it's done and that logs nicely to the log file.
3. A status page that you can see a stream and a box with live tailing of the log file.
4. Maybe a pretty logo thanger

**Comment by skalnik** [comment]
Being worked on the Open Source milestone: https://github.com/github/make_me/issues?milestone=1&state=open
