### ISSUE TITLE
What color plastic is loaded

### ISSUE THREAD

**Issue by johndbritton** [make-me/make-me#77]
I'd like to be able to find out what color plastic is loaded into the machine from the API and hubot.

**Comment by sshirokov** [comment]
I can get down with this. 

But do you mean "see the color that is there" or "Have an API that tells you some sort of information about the pastic"

**Comment by skalnik** [comment]
I guess we could point a camera at it!

**Comment by johndbritton** [comment]
I just want to know what color my thing will be, more info about the plastic would be cool in the future but it has no value to me.

**Comment by johndbritton** [comment]
stale
