### ISSUE TITLE
Clean install, Miracle-Grue seems to not be able to find scons despite being installed via homebrew 

### ISSUE THREAD

**Issue by voodootikigod** [make-me/make-me#91]
Log snippet attached, I did a find /usr/local/ | grep scons and it is present in lib directories but not bin directories, has something changed with scons?

<pre>
...
=> Building deps
make -C vendor
==> Downloading http://download.savannah.gnu.org/releases/avrdude/avrdude-5.11.1.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/avrdude/5.11.1
==> make
==> make install
  /usr/local/Cellar/avrdude/5.11.1: 9 files, 924K, built in 13 seconds
==> Downloading http://downloads.sourceforge.net/scons/scons-2.3.0.tar.gz
######################################################################## 100.0%
==> /usr/bin/gzip scons-time.1
==> /usr/bin/gzip scons.1
==> /usr/bin/gzip sconsign.1
==> /usr/local/opt/python/bin/python2 setup.py install --prefix=/usr/local/Cellar/scons/2.3.0 --standalone-lib --install-data=/usr/local/Cellar/scons/2.3.0/libexec --no-version-script --no-install-man
  /usr/local/Cellar/scons/2.3.0: 7 files, 328K, built in 3 seconds
make grue
cd Miracle-Grue && scons
/bin/sh: scons: command not found
make[2]: *** [Miracle-Grue/bin/miracle_grue] Error 127
make[1]: *** [all] Error 2
make: *** [init] Error 2
</pre>

Any assist would be much appreciated

**Comment by skalnik** [comment]
It's not available as a bin? That's strange, `scons` should be a command available to you via command line. My laptop is managed via [Boxen](http://boxen.github.com/), so mine is in the Homebrew directory that Boxen manages:

```
1.9.3 in make-me/ on master 
› which scons
/opt/boxen/homebrew/bin/scons
```

**Comment by voodootikigod** [comment]
Which scons version?

On Wednesday, July 10, 2013, Mike Skalnik wrote:

> It's not available as a bin? That's strange, scons should be a command
> available to you via command line. My laptop is managed via [Boxen][
> http://boxen.github.com/], so mine is in the Homebrew directory that
> Boxen manages:
> 
> 1.9.3 in make-me/ on master
> › which scons
> /opt/boxen/homebrew/bin/scons
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/make-me/make-me/issues/91#issuecomment-20758052
> .

## 

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod |
GitHubhttp://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
PromoteJS http://promotejs.com/ | Minute With http://minutewith.com/

Help me end the negativity on the internet, share
thishttp://jsconf.eu/2011/an_end_to_negativity.html
.

**Comment by skalnik** [comment]
```
› scons --version
SCons by Steven Knight et al.:
    script: v2.2.0.issue-2856:2676:d23b7a2f45e8[MODIFIED], 2012/08/05 15:38:28, by garyo on oberbrunner-dev
    engine: v2.2.0.issue-2856:2676:d23b7a2f45e8[MODIFIED], 2012/08/05 15:38:28, by garyo on oberbrunner-dev
    engine path: ['/opt/boxen/homebrew/Cellar/scons/2.2.0-boxen1/libexec/scons-local/SCons']
Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012 The SCons Foundation
```

**Comment by voodootikigod** [comment]
Ok current home-brew installs 2.3.0 will try 2.2.0

On Wed, Jul 10, 2013 at 1:50 PM, Mike Skalnik notifications@github.comwrote:

> › scons --version
> SCons by Steven Knight et al.:
>     script: v2.2.0.issue-2856:2676:d23b7a2f45e8[MODIFIED], 2012/08/05 15:38:28, by garyo on oberbrunner-dev
>     engine: v2.2.0.issue-2856:2676:d23b7a2f45e8[MODIFIED], 2012/08/05 15:38:28, by garyo on oberbrunner-dev
>     engine path: ['/opt/boxen/homebrew/Cellar/scons/2.2.0-boxen1/libexec/scons-local/SCons']
> Copyright (c) 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012 The SCons Foundation
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/make-me/make-me/issues/91#issuecomment-20760121
> .

## 

_Chris Williams_

@voodootikigod http://twitter.com/voodootikigod |
GitHubhttp://github.com/voodootikigod

_The things I make that you should check out:_
SaferAging http://www.saferaging.com/ | JSConf http://jsconf.com/ |
PromoteJS http://promotejs.com/ | Minute With http://minutewith.com/

Help me end the negativity on the internet, share
thishttp://jsconf.eu/2011/an_end_to_negativity.html
.

**Comment by voodootikigod** [comment]
I just reverted it to 2.2.0 and worked perfectly.

Steps for those that may follow afterwards:

<pre>
brew uninstall scons
git checkout a5e77c2 /usr/local/Library/Formula/scons.rb
brew install scons
./script/bootstrap
</pre>

**Comment by skalnik** [comment]
Word. We should update this to work with the latest version. Thanks for checking into this! :heartpulse:

**Comment by voodootikigod** [comment]
<3z closing ticket for now!
